### ISSUE TITLE
how to send data to IFrame URL via POST method

### ISSUE THREAD

**Issue by jrehan** [flex-users/flex-iframe#107]
Hi, 

Can anyone explain to me how can i pass data to iframe URL actually i 
want to send data to IFrame URL via POST method and when the form is 
submitted, the server response should appear in the iframe. 

Thanks

**Comment by nicoulaj** [comment]
You can't, as you cannot do it with a normal html iframe.

**Comment by jrehan** [comment]
i think this feature is available in normal html using "target" property. here is the sample code

"form action="someurl.jsp" method="post" target="my_iframe"
  input type="submit" value="Submit" 
/form

-- when the form is submitted, the server response will appear in this iframe --

iframe name="my_iframe" 

/iframe"

**Comment by nicoulaj** [comment]
OK, then you can do just the same with a Flex iframe, as it is just an HTML iframe. You just have to get the frame name and set it as target of your form.

**Comment by jrehan** [comment]
actually there is not target property in flex. neither in form tag nor in httpService. i tried following

mx:Form  target="my_iframe"  !Not supproted
/mx:Form

s:HTTPService id="contactService" url="url.php" 
                       useProxy="false" method="POST" resultFormat="e4x"
                       result="resultHandler(event)" 
                       fault="faultHandler(event)"

/s:HTTPService

plz help to resolve this problem and suggest any alternative :(

**Comment by nicoulaj** [comment]
It would not work. You have to understand how the flex-iframe works to do this kind of trickery: the flex-iframe component is just a "proxy" that executes Javascript (via ExternalInterface), to create/move/refresh/delete/etc a real HTML iframe in the DOM. The name we are talking about here is the name of the HTML iframe. You can try setting debug=true on the iframe and look at the flash log to understand better how it works.
